(dp1
S'output'
p2
S'<class \'gluon.contrib.pymysql.err.InternalError\'> (1048, u"Column \'Especializacion\' cannot be null")'
p3
sS'layer'
p4
S'/home/dayton/web2py/applications/ProyectoFase1/controllers/default.py'
p5
sS'code'
p6
S'# -*- coding: utf-8 -*-\n### required - do no delete\ndef user(): return dict(form=auth())\ndef download(): return response.download(request,db)\ndef call(): return service()\n### end requires\ndef index():\n    return dict()\n\n@auth.requires_login()\ndef catedratico():\n    form = SQLFORM.smartgrid(db.Catedratico,onupdate=auth.archive)\n    return locals()\n\n\ndef error():\n    return dict()\n\nresponse._vars=response._caller(catedratico)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/dayton/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/dayton/web2py/applications/ProyectoFase1/controllers/default.py", line 19, in <module>\n  File "/home/dayton/web2py/gluon/globals.py", line 412, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/dayton/web2py/gluon/tools.py", line 4236, in f\n    return action(*a, **b)\n  File "/home/dayton/web2py/applications/ProyectoFase1/controllers/default.py", line 12, in catedratico\n    form = SQLFORM.smartgrid(db.Catedratico,onupdate=auth.archive)\n  File "/home/dayton/web2py/gluon/sqlhtml.py", line 3056, in smartgrid\n    user_signature=user_signature, **kwargs)\n  File "/home/dayton/web2py/gluon/sqlhtml.py", line 2275, in grid\n    onsuccess=oncreate)\n  File "/home/dayton/web2py/gluon/html.py", line 2304, in process\n    self.validate(**kwargs)\n  File "/home/dayton/web2py/gluon/html.py", line 2241, in validate\n    if self.accepts(**kwargs):\n  File "/home/dayton/web2py/gluon/sqlhtml.py", line 1722, in accepts\n    self.vars.id = self.table.insert(**fields)\n  File "/home/dayton/web2py/gluon/packages/dal/pydal/objects.py", line 731, in insert\n    ret = self._db._adapter.insert(self, self._listify(fields))\n  File "/home/dayton/web2py/gluon/packages/dal/pydal/adapters/base.py", line 746, in insert\n    raise e\nInternalError: (1048, u"Column \'Especializacion\' cannot be null")\n'
p11
s.